apiVersion: apps/v1
kind: Deployment

metadata:
  name: registry
  labels:
    app.kubernetes.io/name: registry

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: registry
  template:
    metadata:
      labels:
        app.kubernetes.io/name: registry
    spec:
      containers:

      - name: registry
        image: docker.io/library/registry:latest
        volumeMounts:
        - name: secret
          mountPath: /secret
        env:
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: 'true'
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /secret/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /secret/tls.key
        # Probes skip certificate validation for HTTPS
        livenessProbe:
          httpGet:
            port: 5000
            scheme: HTTPS
        readinessProbe:
          httpGet:
            port: 5000
            scheme: HTTPS

      - name: spooler
        image: docker.io/tliron/kubernetes-registry-spooler:latest
        volumeMounts:
        - name: secret
          mountPath: /secret
        - name: spool
          mountPath: /spool
        env:
        # Vars with the "REGISTRY_SPOOLER_" prefix become CLI flags 
        - name: REGISTRY_SPOOLER_registry
          value: localhost:5000
        - name: REGISTRY_SPOOLER_certificate
          value: /secret/tls.crt
        - name: REGISTRY_SPOOLER_verbose
          value: '2'
        # A future version of Kubernetes may allow for this:
        # lifecycle:
        #   type: sidecar
        # See: https://github.com/kubernetes/enhancements/blob/master/keps/sig-apps/sidecarcontainers.md
        #      https://banzaicloud.com/blog/k8s-sidecars/
        livenessProbe:
          httpGet:
            port: 8086
            path: /live
        readinessProbe:
          httpGet:
            port: 8086
            path: /ready

      volumes:
      - name: secret
        secret:
          secretName: registry
      - name: spool
        emptyDir: {}

---

apiVersion: cert-manager.io/v1
kind: Issuer

metadata:
  name: registry
  labels:
    app.kubernetes.io/name: registry

spec:
  selfSigned: {}

---

apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: registry
  labels:
    app.kubernetes.io/name: registry

spec:
  secretName: registry
  dnsNames:
  - localhost
  uris:
  - https://github.com/tliron/kubernetes-registry-spooler
  issuerRef:
    name: registry
